### ISSUE TITLE
IoU Calculation

### ISSUE THREAD

**Issue by marckatzenmaier** [alexander-g/Cell-Detection-for-Wood-Anatomy#1]
Hi Alexander,
Thanks for open sourcing the code to the paper. 
When I had a look through your evaluation code I found the IoU calculation function:
```
def coords_IoU(xyset0, xyset1):
    return 2*len(xyset0.intersection(xyset1)) / (len(xyset0) + len(xyset1))
```
If I understand the input parameter correctly I think there is a small mistake in the formula shouldn't it be:

```
def coords_IoU(xyset0, xyset1):
    return len(xyset0.intersection(xyset1)) / (len(xyset0) + len(xyset1)- len(xyset0.intersection(xyset1)))
```
with your formula the IoU can become greater than 1 which shouldn't be possible.
Thanks for your response

**Comment by alexander-g** [comment]
Hi,
you are right that this is not the correct the IoU formula. It's actually the [Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Formula).  However, both are quite [similar](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Difference_from_Jaccard) and range from 0 to 1, values greater than 1 are not possible.
This function is only used to match predicted cells with ground truth cells, thus the rest of the evaluation should be still correct.

**Comment by marckatzenmaier** [comment]
Thanks for the clarification and the quick response.
